### ISSUE TITLE
Switch <C-CR> to another map for compatibilty issues with windows users

### ISSUE THREAD

**Issue by alanfzf** [daliusd/ghlite.nvim#1]
Hey there dude, Alan from reddit here, first of all, let me say well done, so far im loving this plugin, its minimalistic and adjusts to my workflow, its a blessing to have an easy way to review prs within nvim!

On the other side, i've noticed that the default mapping to send a comment on the pr window is mapped to `<C-CR>` this may be a bit of an issue for windows users, as this escape code is not sent by default on windows terminal, the defacto and most popular terminal on windows.

This behavior will make windows users think your plugin doesn't work at all, so i think it would be good, to map this key to something else? maybe like `<localleader>` + `P`?

**Comment by daliusd** [comment]
I will make this configurable.

**Comment by daliusd** [comment]
Check documentation - you can override keybindings now.

**Comment by alanfzf** [comment]
Thank you!
