### ISSUE TITLE
Populate quickfilx list with comment text.

### ISSUE THREAD

**Issue by kuzyo** [daliusd/ghlite.nvim#10]
I'm using touble quickfix list to display loaded comments and noticed that after loading I'm having only file and line numbers. I wonder if you can load part of comment beside line number.

Here is screenshot how trouble quickfix looks with some search results and comparison with loaded comments

<img width="1710" alt="Screenshot 2024-11-21 at 19 02 01" src="https://github.com/user-attachments/assets/799614d8-9b7b-4c9b-b50f-e82dc1c5a6e4">
<img width="1710" alt="Screenshot 2024-11-21 at 19 02 36" src="https://github.com/user-attachments/assets/2b892ad8-6a97-42eb-a93e-19161fcae599">

Here is default quickfix list:

<img width="1710" alt="Screenshot 2024-11-21 at 19 02 55" src="https://github.com/user-attachments/assets/ea648e53-bb17-4ed2-afb7-c62f6c4041ac">

Thank you for the awesome plugin.

**Comment by daliusd** [comment]
Try it now and let me know if that's something what works for you

**Comment by kuzyo** [comment]
Looks great, thank you.
