### ISSUE TITLE
Add command to request changes

### ISSUE THREAD

**Issue by bronzehedwick** [daliusd/ghlite.nvim#11]
**Describe the bug**
This plugin is missing an interface to request changes to a PR.

**To Reproduce**

1. Select a PR: `GHLitePRSelect`
2. See there is no command to request changes.

**Expected behavior**
There is a command, maybe `GHLitePRRequestChanges`, that provides an interface to `gh pr review --request-changes`.

**Comment by daliusd** [comment]
Please check newest version. Request changes requires comment so I have added new keybinding (C<CR> by default) to `GHLitePRAddPRComment` to add comment and request changes. There is still no command in PR view to request changes, but clicking `cc` to comment will open the same view as `GHLitePRAddPRComment`.

**Comment by daliusd** [comment]
Hey. Just note. I have re-implemented request changes as new command `GHLitePRRequestChanges` so it would work the same as `GHLitePRApprove`
