### ISSUE TITLE
colorize pr output

### ISSUE THREAD

**Issue by justinmk** [daliusd/ghlite.nvim#4]
# Problem

Without any extra plugins (I'm assuming diffview.nvim might change the story here), selecting a PR with `GHLitePRSelect` shows a scratch buffer without any highlighting.

# Proposal

https://github.com/neovim/neovim/issues/30415#issuecomment-2368519968 provides a code snippet that shows how `nvim_open_term` can be used to colorize terminal data from tools like `gh`. So if `gh` outputs colorized output, then that raw output can be passed to `nvim_open_term` to get colorized output in a Nvim buffer. This would also avoid `^M` characters appearing in the buffer.

Note: this may require `text=false` here: https://github.com/daliusd/ghlite.nvim/blob/408dbc06cbc258569d74c9c37ac95a7a979a7e91/lua/ghlite/utils.lua#L5

**Comment by daliusd** [comment]
That's really interesting and I will investigate this.

**Comment by daliusd** [comment]
I have played with this and it kinda works. Here is how it looks like:

![image](https://github.com/user-attachments/assets/7ec86fa5-cd9e-4a46-b324-6e099832fbdf)

Notes:

- It looks wrong on light theme.
- The URL to GitHub PR is in the end
- It might look good on dark theme. Colors are nice if used correctly.
- There are some indications that it is CLI output. Like `Use --comments to view the full conversation`

I prefer not to use this unless there are more suggestions how to make it look good.

Code here: https://github.com/daliusd/ghlite.nvim/pull/5

Currently I have added `markdown` `filetype` to PR view and solved `^M` problem by simply replacing `\r` with empty string. It should look better now.

**Comment by justinmk** [comment]
> It looks wrong on light theme.

Does `gh` in a terminal with light theme look different? This is controlled by the user's ANSI color configuration in their terminal.

**Comment by daliusd** [comment]
> > It looks wrong on light theme.
> 
> Does `gh` in a terminal with light theme look different? This is controlled by the user's ANSI color configuration in their terminal.

It looks wrong in terminal as well. I guess that's my problem then.

**Comment by daliusd** [comment]
Sorry I am lying. It looks better but different.

**Comment by daliusd** [comment]
![image](https://github.com/user-attachments/assets/8a227c74-b515-4383-9982-da79a37ae561)

**Comment by justinmk** [comment]
What about with `:set notermguicolors` (and perhaps `:colors default`)?

**Comment by daliusd** [comment]
> What about with `:set notermguicolors` (and perhaps `:colors default`)?

![image](https://github.com/user-attachments/assets/979d3490-b6bb-419f-b24c-fb765a3da569)

**Comment by justinmk** [comment]
What does `gh` output look like when you run it in a Nvim `:terminal`? It should look the same as `nvim_open_term`. If that looks "bad" it's a colorscheme issue.

> Currently I have added `markdown` `filetype` to PR view

If the content is markdown then that sounds like the right approach :)

**Comment by daliusd** [comment]
> What does `gh` output look like when you run it in a Nvim `:terminal`? It should look the same as `nvim_open_term`. If that looks "bad" it's a colorscheme issue.

In `:terminal` it looks good:
![image](https://github.com/user-attachments/assets/66dcda93-e5df-4095-9621-53e7352ba8b4)


> > Currently I have added `markdown` `filetype` to PR view
> 
> If the content is markdown then that sounds like the right approach :)

It is markdown :-)

**Comment by justinmk** [comment]
> It looks wrong on light theme.

Is that with filetype=markdown? That would explain why it looks different vs `:terminal`.

Anyway, if the content is markdown then using `nvim_open_term` is not needed, so feel free to close this.

**Comment by daliusd** [comment]
> > It looks wrong on light theme.
> 
> Is that with filetype=markdown? That would explain why it looks different vs `:terminal`.

No that's without filetype=markdown. You can check the code in this PR https://github.com/daliusd/ghlite.nvim/pull/5/files

> Anyway, if the content is markdown then using `nvim_open_term` is not needed, so feel free to close this.

I think markdown will work now.

**Comment by daliusd** [comment]
Closing as markdown should work.
