### ISSUE TITLE
Error when using GHLightPRDiffview

### ISSUE THREAD

**Issue by kuzyo** [daliusd/ghlite.nvim#6]
Steps to reproduce:
- open git project
- run GHLightPRSelect
- run GHLightPRDiffview

Tricky thing, that if you run GHLightPRCheckout command, diffview works and if after that you switch branch and repeat above steps diffview works as expected too.

<img width="1657" alt="Screenshot 2024-10-31 at 12 33 19" src="https://github.com/user-attachments/assets/16b4e627-bc96-48a8-8476-d4b79591694e">

**Comment by daliusd** [comment]
1. Could you share your ghlite config as well?
2. Are you in main/master branch when you select PR or some branch? Do you select same branch you are in or different one?
3. nvim version.

**Comment by daliusd** [comment]
Extra information: repository where I can reproduce the issue myself. I see problem is with `diffview.nvim` so it might be problem with this command: 

https://github.com/daliusd/ghlite.nvim/blob/7447a1833b50e4c6bb69d9212be0c3d9a96ea7b2/lua/ghlite/diff.lua#L114

**Comment by kuzyo** [comment]
1. Config
```
return {
  'daliusd/ghlite.nvim',
  config = function()
    require('ghlite').setup({
      debug = false,           -- if set to true debugging information is written to ~/.ghlite.log file
      view_split = '',         -- set to empty string '' to open in active buffer
      diff_split = '',         -- set to empty string '' to open in active buffer
      comment_split = 'split', -- set to empty string '' to open in active buffer
      open_command = 'open',   -- open command to use, e.g. on Linux you might want to use xdg-open
      keymaps = {              -- override default keymaps with the ones you prefer
        diff = {
          open_file = 'gf',
          open_file_tab = 'gt',
          open_file_split = 'gs',
          open_file_vsplit = 'gv',
          approve = '<C-A>',
        },
        comment = {
          send_comment = '<C-A>'
        },
        pr = {
          approve = '<C-A>',
        },
      },
    })
  end,
  keys = {
    { '<leader>us', ':GHLitePRSelect<cr>',        silent = true, desc = "GHLite select PR" },
    { '<leader>uo', ':GHLitePRCheckout<cr>',      silent = true, desc = "GHLite checkout PR" },
    { '<leader>uv', ':GHLitePRView<cr>',          silent = true, desc = "GHLite view PR info" },
    { '<leader>up', ':GHLitePRDiff<cr>',          silent = true, desc = "GHLite open diff" },
    { '<leader>ul', ':GHLitePRDiffview<cr>',      silent = true, desc = 'GHLite open diffview' },
    { '<leader>uu', ':GHLitePRLoadComments<cr>',  silent = true, desc = "GHLite load comments into quickfix" },
    { '<leader>ua', ':GHLitePRAddComment<cr>',    silent = true, desc = "GHLite add comment" },
    { '<leader>uc', ':GHLitePRUpdateComment<cr>', silent = true, desc = 'GHLite update comment' },
    { '<leader>ud', ':GHLitePRDeleteComment<cr>', silent = true, desc = 'GHLite delete comment' },
    { '<leader>ug', ':GHLitePROpenComment<cr>',   silent = true, desc = "GHLite open comment in browser" },
  }
}
```
2. After manual checkout into branch that has open and then selecting same pr and running diffview all works.
3. Nvim version
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
````

**Comment by daliusd** [comment]
I think I have fixed this problem https://github.com/daliusd/ghlite.nvim/commit/3085dacc6308fa259fadfe16e159996306ad0c57

It is not ideal fix, but I hope it will work for you.

As well I have added additional note on GHLightPRDiffview https://github.com/daliusd/ghlite.nvim/commit/423fc7250e9af2a722cf31e0f39d852887a6d025

**Comment by kuzyo** [comment]
Just tested and it works flawlessly.
Thank you, closing issue.
