### ISSUE TITLE
fugitive inspired keybindings

### ISSUE THREAD

**Issue by justinmk** [daliusd/ghlite.nvim#9]
Did you consider looking at fugitive for keybinding ideas? ctrl chords (`<c-a>`) are pretty unusual for vim. And for example, in some terminals (still common), `<c-m>` is an alias to `<cr>`, which is a motion that is somewhat useful. `gv` and `gt` are also generally useful, it's surprising to override them by default.

For commit-related stuff, fugitive uses the `c` prefix in its readonly buffers. That works as mnemonic for "comment" or "code review" in the case of ghlite, and harmonizes with the builtin meaning of `c` as "change" . (Other potential prefixes: `r`, `d`).

I suggest these defaults:

```lua
  diff = {
    open_file = 'gf',
    -- Not worth overriding the default "gt" for this functionality.
    -- open_file_tab = 'gt',

    -- "o" is the "standard" established by netrw, vinegar, dirvish, etc.
    open_file_split = 'o',
    open_file_vsplit = 'O',
    approve = 'ca',
  },
  comment = {
    send_comment = 'c<cr>'
  },
  pr = {
    approve = 'ca',
    merge = 'cm',
  },
```

Also in "pr diff mode", it seems natural to map something like `o` or `ca` to `GHLitePRAddPRComment`.

**Comment by daliusd** [comment]
Thanks for suggestions. I will think about it, but overall I like this idea.

**Comment by daliusd** [comment]
I will not add separate keybinding for adding comment in `pr diff mode` as I think it is better to keep single keybinding to add comment both in `pr diff mode` and normal mode.
